title: "Aaishah's Projects"
description: "input words here"
remote_theme: "just-the-docs/just-the-docs"

# Sidebar navigation order
nav_order: 1

# Enable search functionality
search_enabled: true

# GitHub Pages settings
baseurl: "/projects_"  # Change to match your repo name
url: "https://aaishahaslam.github.io"

footer_content: " "
