title: "Aaishah's Projects"
description: "input words here"
remote_theme: "just-the-docs/just-the-docs"

# Sidebar navigation order
nav_order: 1

# Enable search functionality
search_enabled: false

# GitHub Pages settings
baseurl: "/projects_"  # Change to match your repo name
url: "https://aaishahaslam.github.io"

footer_content: " "

nav:
  - title: "Home"
    url: /

  - title: "Projects"
    children:
      - title: "Project 1"
        url: /project1
      - title: "Project 2"
        url: /project2
      - title: "Project 3"
        url: /project3
        # work
include:
  - project1/Retail.sales.project.html
  - images/*

