title: "Aaishah's Projects"
description: "input words here"

remote_theme: "just-the-docs/just-the-docs"

just_the_docs:
  assets:
    css:
      - assets/custom.css

# Sidebar navigation order
nav_order: 1

# Enable search functionality
search_enabled: true

# GitHub Pages settings
baseurl: "/projects"  # Change to match your repo name
url: "https://aaishahaslam.github.io"

footer_content: " "

nav:
  - title: "Home"
    url: /

  - title: "Projects"
    children:
      - title: "Retail Sales Prediction Time Series Project"
        url: /Retail Sales Prediction Time Series Project
      - title: "Boston Housing Pricing Prediction ML Analysis"
        url: /Boston Housing Pricing Prediction ML Analysis
      - title: "LLY Acquisition Analysis Project"
        url: /LLY Acquisition Analysis Project
      - title: "Placeholder"
        url: /Placeholder
        # work
include:
  - project2/boston project.html
  - images/*

