remote_theme: pmarsceill/just-the-docs
title: "Projects"

# Sidebar navigation
just_the_docs:
  nav_order: 1
  has_toc: true
  aux_links:
    "GitHub Repository": "https://github.com/aaishahaslam/projects"

nav:
  - title: "Home"
    url: "/"
  - title: "Retail Sales Project"
    url: "/docs/Retail.sales.project.html"
