remote_theme: pmarsceill/just-the-docs
# Site settings
title: "Aaishah's Website"

# Navigation settings
just_the_docs:
  nav_order: 1
  nav:
    - title: "Home"
      url: "/"
    - title: "Documentation"
      children:
        - title: "Getting Started"
          url: "/getting-started"
        - title: "Examples"
          url: "/examples"
